### ISSUE TITLE
如何只获取一行的所有cell数据呢？

### ISSUE THREAD

**Issue by TonyChenn** [mini-software/MiniExcel#510]
### Description
案例表格：
|id(A)|name(B)|age(C)|
|---|---|---|
|1|tom|3|
|2|kitty|3|

如何只获取一行的所有cell数据呢？
目前通过下方代码可以获取所有行，每一行都是dynamic类型，所以每一行中存在哪些数据是不清楚的，必须依赖知道每一列的key/id。
```csharp
var rows = fs.Query(useHeaderRow: true, sheetName: sheetName).ToList();
var row = rows[0];
// rows 是 List<dynamic> 里面内容不知道，必须通过如下方式
var id_1 = row.A;
var id_2 = row['id']
```
不知道下面这一行就无法得到数据
|id(A)|name(B)|age(C)|
|---|---|---|

**Comment by tomexou** [comment]
Some excel colum titles have special symbols, and the problem you mentioned will occur, so I will use the following method to read excel files.

`
string startCell = "A2";
var rows = stream.Query(useHeaderRow: false, excelType: ExcelType.XLSX, startCell: startCell);

NOT use "useHeaderRow=true", so you will know the row's fileds are row.A, row.B, row.C...etc.
Then your problem is gone. 
`

**Comment by TonyChenn** [comment]
> Some excel colum titles have special symbols, and the problem you mentioned will occur, so I will use the following method to read excel files.
> 
> string startCell = "A2"; var rows = stream.Query(**useHeaderRow: false**, excelType: ExcelType.XLSX, startCell: startCell);
> 
> NOT use "useHeaderRow=true", so you will know the row's fileds are row.A, row.B, row.C...etc. Then your problem is gone.

Thanks，I will have a try.
